### ISSUE TITLE
Error: The "@angular/compiler-cli" package was not properly installed.

### ISSUE THREAD

**Issue by endreolah419** [smorcuend/angular4-boilerplate#1]
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/polaris/Downloads/angular4-boilerplate-master 2/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/polaris/Downloads/angular4-boilerplate-master 2/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

I think this project is not compatible with latest node & npm versions.
My node version is v7.10.0, npm version is 4.2.0

**Comment by semocodev** [comment]
Hi @endreolah419! 
I am using node@8.1.1 & npm@5.0.3 and works fine for me.
Anyway, i have just upgraded some dependencies to latest versions.

Can you pull latest changes from the master branch and reinstall again? (Be sure to delete node_modules)
